version: '3.10'

volumes:
  pg-data:


services:

  bot:
    &base
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python bot.py
    environment:
      - media_path=/srv/media
      - media_root=/media/
      - DB_PORT=5432
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy

  app:
    <<: *base

    ports:
      - 5000:5000
    command: uvicorn asgi:app --host 0.0.0.0 --port 5000 --workers 2

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/service/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U docker" ]
      interval: 2s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yoyo apply --config ./yoyo.ini
    volumes:
      - .:/src
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
